[phases.setup]
nixPkgs = ["python310", "gcc", "pkg-config"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python -m venv --copies /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
dependsOn = ["install"] 
cmds = [". /opt/venv/bin/activate && cd back && python manage.py collectstatic --noinput"]

[start]
cmd = ". /opt/venv/bin/activate && cd back && gunicorn hammer_backendproject.wsgi --bind 0.0.0.0:$PORT --workers 1 --worker-class sync --timeout 45 --keep-alive 2 --max-requests 1000 --max-requests-jitter 100"