# Generated by Django 5.2.4 on 2025-07-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0005_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='complete_50_hour_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='disk_assessment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='employability_skills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enneagram_results',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='No Name', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='gender_identity',
            field=models.CharField(default='They', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='hammer_math',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='osha_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='osha_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passed_osha_10_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='passed_ruler_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='posttest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pretest_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sixteen_types_assessment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
