# Generated by Django 5.2.4 on 2025-07-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0006_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
