# Generated by Django 5.2.4 on 2025-07-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0008_remove_student_email_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='full_name',
        ),
    ]
