# Generated by Django 5.2.4 on 2025-07-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0010_organization_remove_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_name',
        ),
    ]
