# Generated by Django 5.2.4 on 2025-07-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0011_remove_teacher_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
