# Generated by Django 5.2.4 on 2025-08-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0013_teacher_email_teacher_password_alter_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnneagramResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SixteenTypeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='disk_assessment_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enneagram_results',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sixteen_types_assessment_type',
        ),
        migrations.AddField(
            model_name='student',
            name='disc_assessment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hammer_backendapi.discassessment'),
        ),
        migrations.AddField(
            model_name='student',
            name='enneagram_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hammer_backendapi.enneagramresult'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hammer_backendapi.genderidentity'),
        ),
        migrations.AddField(
            model_name='student',
            name='sixteen_types_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hammer_backendapi.sixteentypeassessment'),
        ),
    ]
