# Generated by Django 5.2.4 on 2025-08-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0014_discassessment_enneagramresult_genderidentity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genderidentity',
            old_name='name',
            new_name='gender',
        ),
    ]
