# Generated by Django 5.2.4 on 2025-08-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0015_rename_name_genderidentity_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OshaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='osha_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hammer_backendapi.oshatype'),
        ),
    ]
