# Generated by Django 5.2.4 on 2025-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0016_oshatype_alter_student_osha_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='city_state',
            field=models.CharField(blank=True, help_text="e.g., 'Austin, TX' or 'Los Angeles, CA'", max_length=100, null=True),
        ),
    ]
