# Generated by Django 5.2.4 on 2025-08-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0017_teacher_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='job_interview_skills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='nccer_number',
            field=models.CharField(blank=True, help_text='NCCER credential number', max_length=50, null=True),
        ),
    ]
