# Generated by Django 5.2.4 on 2025-08-27 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0020_region_state_remove_teacher_city_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='state',
        ),
    ]
