# Generated by Django 5.2.4 on 2025-09-26 17:05

import django.db.models.deletion
import hammer_backendapi.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0021_remove_region_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=hammer_backendapi.models.models.student_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='application/pdf', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='hammer_backendapi.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student File',
                'verbose_name_plural': 'Student Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
