# Generated by Django 5.2.4 on 2025-09-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hammer_backendapi', '0022_add_student_file_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfile',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=100),
        ),
    ]
